

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.2  # Remplacez par la dernière version stable de Ruff
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
